/*fichier lesprints.c*/
#include "lesprints.h"

void printFightDistance(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}


void printFightMidle(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

/*******/

void printTireFruit0(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireFruit1(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXX");rouge();printf("øøø");reset();printf("XXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireFruit2(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.XXXXXXXXXXXXXXX");rouge();printf("øøø");reset();printf("XXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireFruit3(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.XXXXXXXX");rouge();printf("øøø");reset();printf("XXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireFruit4(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.X");rouge();printf("øøø");reset();printf("XXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireFruit5(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX______");rouge();printf("øøø");reset();printf("X.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

/*******/
void printTireFruit10(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

void printTireFruit11(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXøøøX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}


void printTireFruit12(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXøøøXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

void printTireFruit13(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXøøøXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

void printTireFruit14(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXøøøXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

/*******/

void printFruitSoin(){
clear();
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");vert_blink();printf("$");reset();printf("XXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");vert_blink();printf("$$$$$");reset();printf("XXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");vert_blink();printf("$");reset();printf("XXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX");vert_blink();printf("$");reset();printf("XXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\X");vert_blink();printf("$$$$$");reset();printf("XX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX");vert_blink();printf("$");reset();printf("XXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");vert_blink();printf("$");reset();printf("XXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");vert_blink();printf("$$$$$");reset();printf("XXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");vert_blink();printf("$");reset();printf("XXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
waitFor(3);
}

/*******/
void printProtectionFruit(){
clear();
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXX/ |\\XX__XXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");
waitFor(3);
}

/*******/

void printTireProtectionFruit0(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.X");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireProtectionFruit1(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.X");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXX");rouge();printf("øøø");reset();printf("XXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}


void printTireProtectionFruit2(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.X");orange();printf("B");reset();printf("XXXXXX");rouge();printf("øøø");reset();printf("XXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireProtectionFruit3(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.X");rouge();printf("øøø");reset();printf("XXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireProtectionFruit4(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXX");orange();printf("B");reset();printf("XXXXXX");rouge();printf("øøø");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.X");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireProtectionFruit5(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");rouge();printf("øøø");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.X");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireProtectionFruit14(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX");rouge();printf("øøø");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireProtectionFruit15(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX.XX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX______");rouge();printf("øøø");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXX");orange();printf("B");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

/*************************************************/

void printTireLegume0(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireLegume1(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XXXXXXXXX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......XXXXXXXX");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____XXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireLegume2(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____XXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireLegume3(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX__");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("X----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("X\\XX");rouge();printf(".");reset();printf("             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

/******/

void printTireLegume10(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

void printTireLegume11(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......XXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____XXXXXXXXXX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXX");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

void printTireLegume12(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

/******/

void printTireProtectionLegume0(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXBXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXBXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void  printTireProtectionLegume1(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XXXXXXXXX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXBXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......XXXXXXXX");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXBXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____XXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXXXBXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void  printTireProtectionLegume2(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXBXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XXXXXXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XBXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("BXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____XXXXXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXBXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void  printTireProtectionLegume3(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXBXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXBXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXBXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXBXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void  printTireProtectionLegume4(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXXXBXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXXXXXXXXXXXXXBXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireProtectionLegume13(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXBXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XXXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("XXXXXXBXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXX");rouge();printf(".");reset();printf("XXXXXBXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____XXXXXXXXXXXXXXXXXXX");rouge();printf(".");reset();printf("XXXXXXXXXXXBXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printTireProtectionLegume14(){

printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXX");rouge();printf(".");reset();printf("XXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXX__");rouge();printf(".");reset();printf("XX");rouge();printf(".");reset();printf("X----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXX");rouge();printf(".");reset();printf("X\\XX");rouge();printf(".");reset();printf("             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXX");rouge();printf(".");reset();printf("XXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

/*******/

void printLegumeProtection(){
clear();
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.BXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");
waitFor(3);
}

/*******/

void printLegumeSoin(){
clear();
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXX$XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXX#\n");
printf("#XXXXXXX$$$$$XXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXX#\n");
printf("#XXXXXXXXX$XXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXX#\n");
printf("#XXXXXXXXXXX$XXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXX#\n"); 
printf("#XXXXXXXXX$$$$$XX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXX#\n");
printf("#XXXXXXXXXXX$XXXXX....XXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XX$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXX#\n");
printf(" ####################################################################################\n");
waitFor(3);
}

/*******/

void printFruitAvancement0(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

void printFruitAvancement1(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXX#\n");
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf(" ####################################################################################\n");

}

void printFruitAvancement2(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXXXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXXXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXXXXXXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXXXXXXXXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXXXXXXXXXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XXXXXXXXXX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XXXXXXXXXX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XXXXXXXXXX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XXXXXXXXXX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXXXXXXXXXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXXXXXXXXXX#\n");
printf(" ####################################################################################\n");

}


/******/

void printLegumeAvancement0(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

void printLegumeAvancement1(){
printf(" ####################################################################################\n");
printf("#XXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXXXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

void printLegumeAvancement2(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXX#\n");
printf("#XXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX| | |/  |XXXXX#\n");
printf("#XXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\| /  /XXXXXX#\n");
printf("#XXXXXXXXXXXXXXX_______XX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXX----______---XXXX#\n");
printf("#XXXXXXXXXXXXXXXX......X.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\XX/             \\XXX#\n"); 
printf("#XXXXXXXXXXXXXXXX_____X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X/              \\XX#\n");
printf("#XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.|              |XX#\n");
printf("#XXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|              |XX#\n");
printf("#XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\              /XX#\n");
printf("#XXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\            /XXX#\n");
printf("#XXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---______--XXXX#\n");
printf(" ####################################################################################\n");

}

/********************************************/

void printTireFruitOK(){
	clear();
	printTireFruit0();
	waitFor(1);
	clear();
	printTireFruit1();
        waitFor(1);
	clear();
	printTireFruit2();
        waitFor(1);
	clear();
	printTireFruit3();
        waitFor(1);
	clear();
	printTireFruit4();
        waitFor(1);
	clear();
	printTireFruit5();
	waitFor(1);
}


void printTireLegumeOK(){
	clear();
	printTireLegume0();
	waitFor(1);
	clear();
	printTireLegume1();
        waitFor(1);
	clear();
	printTireLegume2();
        waitFor(1);
	clear();
	printTireLegume3();
        waitFor(1);
}

void printTireFruitDistance(){
	clear();
	printTireFruit10();
	waitFor(1);
	clear();
	printTireFruit11();
        waitFor(1);
	clear();
	printTireFruit12();
        waitFor(1);
	clear();
	printTireFruit13();
        waitFor(1);
	clear();
	printTireFruit14();
	waitFor(1);
}

void printTireLegumeDistance(){
	clear();
	printTireLegume10();
	waitFor(1);
	clear();
	printTireLegume11();
        waitFor(1);
	clear();
	printTireLegume12();
        waitFor(1);
}

void printTireFruitProtection(){
	clear();
	printTireProtectionFruit0();
	waitFor(1);
	clear();
	printTireProtectionFruit1();
        waitFor(1);
	clear();
	printTireProtectionFruit2();
        waitFor(1);
	clear();
	printTireProtectionFruit3();
        waitFor(1);

}

void printTireLegumeProtection(){
	clear();
	printTireProtectionLegume0();
	waitFor(1);
	clear();
	printTireProtectionLegume1();
        waitFor(1);
	clear();
	printTireProtectionLegume2();
        waitFor(1);
	clear();
	printTireProtectionLegume3();
        waitFor(1);
	clear();
	printTireProtectionLegume4();
	waitFor(1);
}

void printTireFruitProtectionPass(){
	clear();
	printTireProtectionFruit0();
	waitFor(1);
	clear();
	printTireProtectionFruit1();
        waitFor(1);
	clear();
	printTireProtectionFruit2();
        waitFor(1);
	clear();
	printTireProtectionFruit3();
        waitFor(1);
    clear();
	printTireProtectionFruit14();
        waitFor(1);
	clear();
	printTireProtectionFruit15();
        waitFor(1);
}

void printTireLegumeProtectionPass(){
	clear();
	printTireProtectionLegume0();
	waitFor(1);
	clear();
	printTireProtectionLegume1();
        waitFor(1);
	clear();
	/*printTireProtectionLegume2();
        waitFor(1);
	clear();*/
	printTireProtectionLegume13();
        waitFor(1);
	clear();
	printTireProtectionLegume14();
	waitFor(1);
}
    
void printFruitAvance(){
	clear();
	printFruitAvancement0();
	waitFor(1);
	clear();
	printFruitAvancement1();
	waitFor(1);
	clear();
	printFruitAvancement2();
	waitFor(1);
}

void printLegumeAvance(){
	clear();
	printLegumeAvancement0();
	waitFor(1);
	clear();
	printLegumeAvancement1();
	waitFor(1);
	clear();
	printLegumeAvancement2();
	waitFor(1);
}

void printFruitRecule(){
	clear();
	printFruitAvancement2();
	waitFor(1);
	clear();
	printFruitAvancement1();
	waitFor(1);
	clear();
	printFruitAvancement0();
	waitFor(1);
}

void printLegumeRecule(){
	clear();
	printLegumeAvancement2();
	waitFor(1);
	clear();
	printLegumeAvancement1();
	waitFor(1);
	clear();
	printLegumeAvancement0();
	waitFor(1);
}

/**/

void printFightCac(){
printf(" ####################################################################################\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\X|X/XXXXXXXXXXXXXXXXXXXXX/\\XXXXXXXXXXXXXXxxxxxxxxxXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\|/XXXXXXXXXXXXXXXXXXXXX/ |\\XX__XXXXXXXXxxxxxxxxxXXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX________XXXXXXXXXXXXXXXXX| | |/  |XXXXXXXXxxxxxxxxxXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX........XXX.XXXXXXXXXXXXXX\\| /  /XXXXXXXXXXxxxxxxxxxX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_______XX.XX.XX___XXXX----______---XXXXXxxxxxxxxxXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX......X.XXXX.XXXX\\XX/             \\XXXXXXXxxxxxxxxxX#\n"); 
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_____X.XXXXXXXXXXX\\X/              \\XXXXXxxxxxxxxxXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXX.|              |XXXXXxxxxxxxxxXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX___XXXXXXXXXXXXXXX|              |XXXxxxxxxxxxXXXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXX\\              /XXXXXxxxxxxxxxXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXX\\            /XXXXXXxxxxxxxxxXX#\n");
printf("#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXX---______--XXXXXXXXXXXXXXXXXX#\n");
printf(" ####################################################################################\n");
}

void printGameOver(){
    clear();
    vert_blink();
    printf(" #############################################################################\n");
    printf("#                                                                             #\n");
    printf("#  /$$$$$$$  /$$$$$  /$$      /$$ /$$$$$$$$                                   #\n");
    printf("# /$$___  $$/$$_  $$| $$$    /$$$| $$_____/                                   #\n");
    printf("# |$$   \\__/|$$  \\$$| $$$$  /$$$$| $$                                         #\n");
    printf("# |$$ / $$$$|$$$$$$$| $$ $$/$$ $$| $$$$$                                      #\n");
    printf("# |$$|_   $$|$$_  $$| $$  $$$| $$| $$__/                                      #\n");
    printf("# |$$   \\ $$|$$ | $$| $$ \\ $ | $$| $$                                         #\n");
    printf("#  \\ $$$$$$/|$$ | $$| $$  \\/ | $$| $$$$$$$$                                   #\n");
    printf("#   ______/ |_/ |__/|__/     |__/|________/                                   #\n");
    printf("#                                   /$$$$$$                                   #\n");
    printf("#                                  /$$    $$                                  #\n");
    printf("#                                  |$$    $$ /$$  /$$ /$$$$$$  /$$$$$$$       #\n");
    printf("#                                  |$$    $$| $$ /$$//$$__  $$/$$__   $$      #\n");
    printf("#                                  |$$    $$\\ $$/$$/ $$$$$$$$| $$  \\__/       #\n");
    printf("#                                  |$$    $$ \\ $$$/| $$_____/| $$             #\n");
    printf("#                                  | $$$$$$/  \\ $/ | $$$$$$$ | $$             #\n");
    printf("#                                  \\______/    \\/  \\_______/ |__/             #\n");
    printf("#                                                                             #\n");
    printf(" ############################################################################# \n"); 
    reset();
    waitFor(3);
}
/**/

void printfWinner(){
    clear();
    magenta();
    printf(" ############################################################################ \n");
    printf("#                                                                            #\n");
    printf("#                                                                            #\n");
    printf("#                                                                            #\n");
    printf("# /$$     /$$ /$$$$$$   /$$   /$$       /$$       $$  /$$$$$$ /$$   /$$      #\n");
    printf("# \\ $$   /$$//$$__   $$| $$  | $$      | $$       $$ |  $$__/| $$$ | $$      #\n");
    printf("#  \\ $$ /$$/| $$   \\ $$| $$  | $$      | $$   $   $$ |  $$   | $$$$| $$      #\n");
    printf("#   \\ $$$$/ | $$   | $$| $$  | $$      | $$  $$$  $$ |  $$   | $$ $$ $$      #\n");
    printf("#    \\ $$/  | $$   | $$| $$  | $$      | $$ $$ $$ $$ |  $$   | $$  $$$$      #\n");
    printf("#    | $$   | $$   | $$| $$  | $$      | $$$$__ $$$$ |  $$   | $$\\  $$$      #\n");
    printf("#    | $$   | $$   | $$| $$  | $$      | $$$/ \\ $$$  |  $$   | $$\\   $$      #\n");
    printf("#    | $$   |  $$$$$$ /|  $$$$$$/      | $$/   \\ $$ / $$$$$$ | $$ \\   $      #\n");
    printf("#    |__/   \\________/ \\_______/       |__/     \\__/|_______/|__/  \\__/      #\n");
    printf("#                                                                            #\n");
    printf("#                                                                            #\n");
    printf("#                                                                            #\n");
    printf("#                                                                            #\n");
    printf("#                                                                            #\n");
    printf("#                                                                            #\n");
    printf(" ############################################################################ \n");
    reset();
    waitFor(3);
}

void printVainqueur(){
    printf("\n");
    jaune();
	printf("\
 _    __ ___     ____ _   __ ____   __  __ ______ __  __ ____\n\
| |  / //   |   /  _// | / // __ \\ / / / // ____// / / // __ \\ \n\
| | / // /| |   / / /  |/ // / / // / / // __/  / / / // /_/ /\n\
| |/ // ___ | _/ / / /|  // /_/ // /_/ // /___ / /_/ // _, _/ \n\
|___//_/  |_|/___//_/ |_/ \\___\\_\\\\____//_____/ \\____//_/ |_|  \n\n");
    reset();
}

void printFruits(){                                                             
	rouge();
    printf("\
    ______ ____   __  __ ____ ______ _____\n\
   / ____// __ \\ / / / //  _//_  __// ___/\n\
  / /_   / /_/ // / / / / /   / /   \\__ \\ \n\
 / __/  / _, _// /_/ /_/ /   / /   ___/ /\n\
/_/    /_/ |_| \\____//___/  /_/   /____/");                                       
    reset();
}

void printLegumes(){
    vert_blink();
    printf("\
    __     ______ ______ __  __ __  ___ ______ _____ \n\
   / /    / ____// ____// / / //  |/  // ____// ___/ \n\
  / /    / __/  / / __ / / / // /|_/ // __/   \\__ \\  \n\
 / /___ / /___ / /_/ // /_/ // /  / // /___  ___/ /  \n\
/_____//_____/ \\____/ \\____//_/  /_//_____/ /____/  \n"); 
    reset();
}

void printExaequo(){
    jaune();
    printf("\
    ______ _  __        ___     ______ ____   __  __ ____ \n\
   / ____/| |/ /       /   |   / ____// __ \\ / / / // __ \\ \n\
  / __/   |   /______ / /| |  / __/  / / / // / / // / / / \n\
 / /___  /   |/_____// ___ | / /___ / /_/ // /_/ // /_/ /  \n\
/_____/ /_/|_|      /_/  |_|/_____/ \\___\\_\\____/ \\____/   \n");
    reset();
}
